INSERT INTO item (nome, tipo, preco, descricao)
VALUES
("Poção de Vida", "Consumível", 3, "Restaura 5 pontos de vida."),
("Poção de Mana", "Consumível", 3, "Restaura 5 pontos de mana."),
("Poção de Força", "Consumível", 5, "Aumenta a força em 2 pontos por 1 hora."),
("Poção de Agilidade", "Consumível", 5, "Aumenta a agilidade em 2 pontos por 1 hora."),
("Poção de Constituição", "Consumível", 5, "Aumenta a constituição em 2 pontos por 1 hora."),
("Poção de Mente", "Consumível", 5, "Aumenta a mente em 2 pontos por 1 hora."),
("Poção de Carisma", "Consumível", 5, "Aumenta o carisma em 2 pontos por 1 hora."),
("Poção de Determinação", "Consumível", 5, "Aumenta a determinação em 2 pontos por 1 hora."),
("Elixir da Vida", "Consumível", 8, "Aumenta a vida máxima em 3 pontos por 1 hora."),
("Elixir da Mana", "Consumível", 8, "Aumenta a mana máxima em 3 pontos por 1 hora."),
("Elixir da Agitação", "Consumível", 10, "Ganha 1 ponto extra de adrenalina a cada par de pontos xp ganhos por uma hora"),
("Espada", "Arma", 12, "Ganha a habilidade 'Golpe Cortante'"),
("Machado", "Arma", 12, "Ganha a habilidade 'Corte Pesado'"),
("Lança", "Arma", 12, "Ganha a habilidade 'Golpe Alongado'"),
("Cajado", "Arma", 12, "Ganha a habilidade 'Golpe Magico'"),
("Escudo", "Armadura", 10, "Ganha a habilidade 'Defesa Aumentada'"),
("Peitoral", "Armadura", 15, "Ganha mais 1 ponto de durabilidade nas barras de armadura que não estejam quebradas"),
("Botas", "Armadura", 15, "Ganha mais 1 ponto de durabilidade nas barras de armadura que não estejam quebradas"),
("Capacete", "Armadura", 15, "Ganha mais 1 ponto de durabilidade nas barras de armadura que não estejam quebradas"),
("Bracelete", "Armadura", 10, "Ganha a habilidade 'Defesa Leve'"),
("Cinto de Força", "Equipavel", 8, "Aumenta a força em 2 pontos."),
("Anel de Agilidade", "Equipavel", 8, "Aumenta a agilidade em 2 pontos."),
("Colar de Constituição", "Equipavel", 8, "Aumenta a constituição em 2 pontos."),
("Tiara da Mente", "Equipavel", 8, "Aumenta a mente em 2 pontos."),
("Anel de Carisma", "Equipavel", 8, "Aumenta o carisma em 2 pontos."),
("Cinto de Determinação", "Equipavel", 8, "Aumenta a determinação em 2 pontos."),
("Anel de Proteção", "Equipavel", 10, "Aumenta a defesa em 2 pontos."),
("Amuleto de Proteção", "Equipavel", 10, "Aumenta a defesa em 2 pontos."),
("Cinto de Proteção", "Equipavel", 10, "Aumenta a defesa em 2 pontos."),
("Bracelete de Proteção", "Equipavel", 10, "Aumenta a defesa em 2 pontos."),
("Botas de Velocidade", "Equipavel", 8, "Aumenta a velocidade em 2 pontos."),
("Capa da Invisibilidade", "Equipavel", 20, "Permite ficar invisível por 1 hora."),
("Capa da Agilidade", "Equipavel", 10, "Aumenta a agilidade em 2 pontos."),
("Capa da Força", "Equipavel", 10, "Aumenta a força em 2 pontos."),
("Capa da Constituição", "Equipavel", 10, "Aumenta a constituição em 2 pontos."),
("Capa da Mente", "Equipavel", 10, "Aumenta a mente em 2 pontos."),
("Capa do Carisma", "Equipavel", 10, "Aumenta o carisma em 2 pontos."),
("Capa da Determinação", "Equipavel", 10, "Aumenta a determinação em 2 pontos."),
("Capa do Poder", "Equipavel", 15, "Aumenta o poder mágico em 2 pontos."),
("Capa da Resistência", "Equipavel", 15, "Aumenta a resistência mágica em 2 pontos."),
("Capa da Velocidade", "Equipavel", 10, "Aumenta a velocidade em 2 pontos.");

